Baruk/Baruk/Controllers/InformationController.cs
using Baruk.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Baruk.Controllers
{
    public class InformationController : Controller
    {
        // GET: Information
        [HttpGet]
        public ActionResult InformationForm()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> InformationForm(FormCollection C)
        {
            string Name = C["name"];
            string Email = C["email"];
            string Message = C["message"];
            if (ModelState.IsValid)
            {
                var message = new MailMessage();
                message.To.Add(new MailAddress(Email));  // replace with valid value 
                message.From = new MailAddress("barukcrossfit@gmail.com");  // replace with valid value
                message.Subject = "Infomación de Baruk";
                message.Body = string.Format("Gracias por contactarnos " + Name + ", nos aseguremos de contactarlo por medio de este medio" +
                        " o bien al número ingresado (+506 8326 0333) para brindarle más información del servicio en questión. \n \n" +
                        "Atentamente, Felipe Chacon - Socio.");
                message.IsBodyHtml = true;
                using (var smtp = new SmtpClient())
                {
                    var credential = new NetworkCredential
                    {
                        UserName = "barukcrossfit@gmail.com",  // replace with valid value
                        Password = "ulacit2019"  // replace with valid value
                    };
                    smtp.Credentials = credential;
                    smtp.Host = "smtp.gmail.com";//address webmail
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    await smtp.SendMailAsync(message);

                    return View();
                }
            }
            return View();
        }



        // GET: Information
        public ActionResult Gallery()
        {
            return View();
        }

        // GET: Information
        public ActionResult WhoAreWe()
        {
            return View();
        }

        // GET: Information
        public ActionResult Calendar()
        {
            return View();
        }

        public ActionResult _Denied()
        {
            return View();
        }
    }
}

Baruk/Baruk/Views/Information/Calendar.cshtml
@if (Session["UserType"] != null)
{
<div class="container body-content">
    <table class="card white-text center" style="margin-bottom:3%; margin-top:5%">
        <thead>
            <tr class="teal darken-1">
                <th class="center">Símbolos:</th>
                <th class="center">Clases regulares: <img src="~/Public/img/weightSmall.png" alt="Alternate Text" /></th>
                <th class="center">Barbell club: <img src="~/Public/img/weightliftingSmall.png" alt="Alternate Text" /></th>
                <th class="center">Gimnasia: <img src="~/Public/img/gymnasticsSmall.png" alt="Alternate Text" /></th>
            </tr>
        </thead>
    </table>

    <table class="card white-text center highlight grey lighten-2">
        <thead>
            <tr class="teal darken-2">
                <th class="center">Horario</th>
                <th class="center">Lunes</th>
                <th class="center">Martes</th>
                <th class="center">Miercoles</th>
                <th class="center">Jueves</th>
                <th class="center">Viernes</th>
                <th class="center">Sábado</th>
            </tr>
        </thead>
        <tbody>
            <tr class="center">
                <td class="teal darken-1 center"><b>5:00 am</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>

            </tr>
            <tr>
                <td class="teal darken-1 center"><b>6:00 am</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center black-text">10:00 am <img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>10:30 am</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center black-text">11:00 am <img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>11:30 am</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center black-text">12:00 md <img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>4:00 pm</b></td>
                <td colspan="5" class="center black-text">
                    Open&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;Box
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;Competidores
                </td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>5:00 pm</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>6:00 pm</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>7:00 pm</b></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
                <td class="center"><img src="~/Public/img/weightSmall.png" alt="weightIcon" /></td>
            </tr>
            <tr>
                <td class="teal darken-1 center"><b>8:00 pm</b></td>
                <td class="center black-text">Open</td>
                <td class="center"><img src="~/Public/img/weightliftingSmall.png" alt="weightLift" /></td>
                <td class="center black-text">Box</td>
                <td class="center"><img src="~/Public/img/gymnasticsSmall.png" alt="gymnastics" /></td>
                <td colspan="2" class="center black-text">Competidores</td>
            </tr>
        </tbody>
    </table>
</div>
        }
        @if (Session["UserType"] == null)
        {
            Response.Redirect("~/Information/_Denied");
        }

Baruk/Baruk/Views/Information/Gallery.cshtml
<div class="container body-content">
    @*<div class="col s12 m7">
            <div class="card  teal darken-4 hoverable">
                <div class="center">
                    <span class="card-title white-text" style="font-size: 55px">¿Por qué elegirnos?</span>
                </div>
            </div>
            <div class="card horizontal hoverable">
                <div class="card-image">
                    <img src="https://lorempixel.com/100/190/nature/6">
                </div>
                <div class="card-stacked teal darken-3">
                    <div class="card-content white-text">
                        <p>
                            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                            totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                        </p>
                    </div>
                </div>
            </div>
        </div>
            <ul class="collapsible white-text teal darken-1 hoverable">
                <li class="white-text">
                    <div class="collapsible-header teal darken-3"><i class="material-icons">filter_1</i>Primero</div>
                    <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                </li>
                <li>
                    <div class="collapsible-header teal darken-3"><i class="material-icons">filter_2</i>Segundo</div>
                    <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                </li>
                <li>
                    <div class="collapsible-header teal darken-3"><i class="material-icons">filter_3</i>Tercero</div>
                    <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                </li>
            </ul>*@


    <div class="card z-depth-3">
        <div class="slider" style="margin-top: 5%; margin-bottom: 5%;">
            <ul class="slides">
                <li>
                    <img src="~/Public/img/sample1.jpg">
                    <div class="caption center-align">
                        <h3>PalmaWod 2019</h3>
                        <h5 class="light grey-text text-lighten-3">Competencia a Nivel Nacional</h5>
                    </div>
                </li>
                <li>
                    <img src="~/Public/img/sample2.jpg">
                    <div class="caption left-align  black-text">
                        <h3>Competencia Interna</h3>
                        <h5 class="light black-text flow-text">Mujer Modificado</h5>
                    </div>
                </li>
                <li>
                    <img src="~/Public/img/sample3.jpg">
                    <div class="caption center-align white-text">
                        <h3>Staff</h3>
                        <h5 class="light grey-text text-lighten-3"></h5>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

Baruk/Baruk/Views/Information/InformationForm.cshtml
@{
    ViewData["Title"] = "InformationForm";
}
<div class="container body-content">
    <div class="row">
        <form method="post" class=" card col s12 blue-grey darken-1 z-depth-3" style="margin-top: 2%;">
            <div class="center">
                <span class="card-title white-text" style="font-size: 55px">Contáctenos</span>
            </div>
            @using (Html.BeginForm("InformationForm", "Information", FormMethod.Post, new { @class = "contact-list", id = "contacts_form", role = "form", target = "_blank" }))
            {
                @Html.TextBox("name", null, new { @class = "form_item validate", @required = "required", placeholder = "Nombre", type = "text" })
                @Html.TextBox("email", null, new { @class = "form_item validate", @required = "required", placeholder = "Correo", type = "email" })
                @Html.TextBox("message", null, new { @class = "form_item validate", @required = "required", placeholder = "Mensaje", type = "text" })

                <div class="row center">
                    <button class="btn waves-effect waves-light light-green accent-4" type="submit" name="action">
                        Enviar
                        <i class="material-icons right">send</i>
                    </button>
                </div>

            }
        </form>
    </div>
    <strong>Email:</strong>   <a class="teal-text text-darken-4" href="mailto:crossfit.baruk@gmail.com">crossfit.baruk@gmail.com</a><br />
</div>

Baruk/Baruk/Views/Information/WhoAreWe.cshtml
<div class="container body-content">
    <div class="col s12 m7 ">
        <div class="card blue-grey darken-4 hoverable">
            <div class="center">
                <span class="card-title white-text" style="font-size: 55px">¿Quienes somos?</span>
            </div>
        </div>
        <div class="card horizontal blue-grey darken-1 hoverable">
            <div class="card-image">
                <img src="~/Public/img/Quienes somos.jpg" height="350" width="500">
            </div>
            <div class="card-stacked">
                <div class="card-content  white-text">
                    <p style="text-align: justify">
                        Somos CrossFit Baruk, un centro de entrenamiento funcional que se ubica en la Uruca - San José; el CrossFit es un tipo de entrenamiento físico basado en ejercicios funcionales constantemente variados, ejecutados a alta intensidad. Además, se practican diversas disciplinas como: levantamiento olímpico, gimnasia y endurance. Todos los movimientos se aprenden progresivamente.
                        Las clases tiene una duración de aproximadamente 1 hora, contamos con diversos horarios, servicios como terapia física y nutrición y amplio estacionamiento.
                        Contamos con experiencia a nivel profesional, los entrenadores están certificados en las diversas áreas para desarrollar dicha labor.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m6 left">
            <div class="card blue-grey darken-1 hoverable">
                <div class="card-image">
                    <img src="https://scontent-atl3-1.cdninstagram.com/vp/2140b0e5dc689860ba7d8524d656d7f3/5D8FCD41/t51.2885-15/e35/17127089_390213524692328_9072363044016750592_n.jpg?_nc_ht=scontent-atl3-1.cdninstagram.com" height="300" width="100" />
                </div>
                <div class="card-content white-text">
                    <span class="card-title white-text">Objetivos Como Box</span>
                    <p style="text-align:justify;">
                        +Incentivar un estilo de vida saludable por medio de un entrenamiento funcional ejecutado a alta intensidad para mejorar las capacidades físicas.<br />
                        +Propiciar un ambiente agradable y familiar por medio de un servicio al cliente de forma integral para céntranos en las necesidades del cliente.
                    </p>
                </div>
            </div>
        </div>
        <div class="col s12 m6">
            <div class="card blue-grey darken-1 hoverable">
                <div class="card-image">
                    <img src="https://i.ytimg.com/vi/kWFdxw5qKm8/maxresdefault.jpg" height="250" width="150">
                </div>
                <div class="card-content  white-text">
                    <p style="text-align:justify;">
                        <span class="card-title">Competencias Nacionales</span>
                        Brindamos una programación adicional para las personas que desean competir a nivel nacional en diversas categorías como: escaldas, intermedio y RX.
                        Hemos participado en competencias como: Palmawod, RedSky, Costa Rica RX Challenge, WodFest, Copa Independencia, entre otras.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

Baruk/Baruk/Views/Information/_Denied.cshtml
<div class="container body-content">
    <div class="row">
        <br />
        <form class=" card col s12 #9e9e9e grey" style="margin-top: 2%;">
            <br /><br />
            <div class="row">
                <center> <i class="large material-icons">error_outline</i> </center>
            </div>
            <div class="row">
                <center>
                    <h1>Acceso Denegado</h1>
                </center>
            </div>
            <div class="row">
                <center>
                    <h5>No posee los permisos necesarios para visualizar este contenido.</h5>
                </center>
            </div>
            <br /><br />
        </form>
    </div>
</div>